### PR TITLE
Changed allocation from static to dynamic to avoid compiler warning

### PR DESCRIPTION
**Pull request by LucasVisscher**

### CODE REVIEW

**Comment by bast** [comment]
I am applying this patch now to the code in DIRAC (I am working on a branch there).

**Comment by bhelmichparis** [comment]
@LucasVisscher could you also deallocate the dynamically allocated array?

**Comment by bast** [comment]
I will port this over to DIRAC ...

**Comment by LucasVisscher** [comment]
> @LucasVisscher could you also deallocate the dynamically allocated array?

done

**Pull request merged**
